apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mh3gpu99j-go-gitops
  description: This is GitOps manifest for mh3gpu99j-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=mh3gpu99j-go
    backstage.io/kubernetes-id: mh3gpu99j-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: mh3gpu99j-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:mh3gpu99j-go
